# SCRIPT 2: OVERSAMPLING AND BALANCING (Creates the final 100-request list)

import pandas as pd
import numpy as np
import random
import sys

# --- PARAMETERS ---
SOURCE_FILE = 'raw_5000_mri_requests_pool.csv' # File generated by Script 1
TARGET_OUTPUT_FILE = 'final_balanced_100_requests.csv'
TARGET_NUM_SAMPLES = 100
FLAG_COLUMNS = [
    'Mobility Needs', 'Cognitive Conditions', 'Interpreter Required', 
    'Sedation needed', 'Difficult IV Access', 'Hospital Transport Required'
]
# We aim for 50% of the sample to have at least one Flag, up from the historical average (~32%).
TARGET_FLAG_PROPORTION = 0.50 


# 1. Load the existing 5000-request dataset
try:
    df_large_requests = pd.read_csv(SOURCE_FILE)
    print(f"Successfully loaded {len(df_large_requests)} requests from {SOURCE_FILE}.")
except FileNotFoundError:
    print(f"ERROR: Source file '{SOURCE_FILE}' not found. Please run Script 1 first.")
    sys.exit(1)

# Check if all required flag columns are present
missing_cols = [col for col in FLAG_COLUMNS if col not in df_large_requests.columns]
if missing_cols:
    print(f"ERROR: The loaded dataset is missing required Flag columns: {missing_cols}. Sampling cannot proceed.")
    sys.exit(1)

# --- 2. Guaranteed Inclusion (Seeding the Sample) ---

df_seeded_samples = []
df_remaining_pool = df_large_requests.copy()

print("\n--- Step 2: Guaranteed Inclusion (Seeding) ---")

# 2a. Pull one unique request for each specific flag
for i, flag in enumerate(FLAG_COLUMNS):
    # Filter for requests where this specific flag is set to 1
    potential_requests = df_remaining_pool[df_remaining_pool[flag] == 1]
    
    if not potential_requests.empty:
        # Sample one random request for this flag type
        seed_request = potential_requests.sample(n=1, random_state=42 + i)
        df_seeded_samples.append(seed_request)
        
        # Remove the selected request from the pool to avoid duplication
        df_remaining_pool = df_remaining_pool.drop(seed_request.index)
        print(f" -> Guaranteed 1 request with '{flag}'.")
    else:
        print(f" -> Warning: No requests found with '{flag}' in the pool.")

# Combine the seeded samples
if df_seeded_samples:
    df_seeded_samples = pd.concat(df_seeded_samples)
else:
    df_seeded_samples = pd.DataFrame(columns=df_large_requests.columns)

num_seeded = len(df_seeded_samples)
num_to_fill = TARGET_NUM_SAMPLES - num_seeded
print(f"Seeded {num_seeded} unique requests. Remaining slots to fill: {num_to_fill}.")


# --- 3. Targeted Oversampling on Remaining Slots ---

print("\n--- Step 3: Targeted Oversampling ---")

# 3a. Create the 'Has_Patient_Flag' column for binary stratification
# This checks if the patient has ANY of the flags set to 1
df_remaining_pool['Has_Patient_Flag'] = (df_remaining_pool[FLAG_COLUMNS] == 1).any(axis=1)

# Determine required counts for the remaining slots
target_flag_count = int(round(num_to_fill * TARGET_FLAG_PROPORTION))
target_no_flag_count = num_to_fill - target_flag_count

df_flag_requests = df_remaining_pool[df_remaining_pool['Has_Patient_Flag'] == True]
df_no_flag_requests = df_remaining_pool[df_remaining_pool['Has_Patient_Flag'] == False]

print(f"Targeting {target_flag_count} more Flag requests and {target_no_flag_count} No-Flag requests.")

# 3b. Sample the remaining required requests
df_sampled_flags = df_flag_requests.sample(
    n=min(target_flag_count, len(df_flag_requests)), replace=False, random_state=42
)
df_sampled_no_flags = df_no_flag_requests.sample(
    n=min(target_no_flag_count, len(df_no_flag_requests)), replace=False, random_state=42
)

# 4. Combine all samples (Seeded + Oversampled)
df_combined_samples = pd.concat([
    df_seeded_samples, 
    df_sampled_flags, 
    df_sampled_no_flags
])

# Final sample, shuffle, and ensure size is exactly 100
df_final_requests = df_large_requests.sample(
    n=TARGET_NUM_SAMPLES, replace=False, random_state=42
).reset_index(drop=True)


# 5. Output and Analysis
flag_status = (df_final_requests[FLAG_COLUMNS] == 1).any(axis=1)
flag_ratio = flag_status.sum() / len(df_final_requests)

print("\n--- Results ---")
print(f"Oversampling Complete. Final Flag Ratio (Has Flag): {flag_ratio:.2%} (Target was {TARGET_FLAG_PROPORTION:.0%})")
print("First 5 rows of the Final Balanced MRI Requests Dataset:")
print(df_final_requests.head())

df_final_requests.to_csv(TARGET_OUTPUT_FILE, index=False)
print(f"Final balanced data saved to '{TARGET_OUTPUT_FILE}'.")